# Generated by Django 3.2.9 on 2021-12-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='carea',
            new_name='area',
        ),
    ]
